### ISSUE TITLE
Pipe's leftmost function should be able to accept more than one argument

### ISSUE THREAD

**Issue by OlegAlexander** [slavaGanzin/ramda.py#15]
Hello and thank you for porting ramdajs to Python!

I'd like to report an inconsistency between ramdajs's `pipe` and yours. In ramdajs, pipe's leftmost function can accept more than one argument. The documentation says: "The first argument may have any arity; the remaining arguments must be unary." For example, this works in ramdajs:

```javascript
R.pipe(R.add, R.negate)(1, 2); // -3
```
However, in Python, the same code fails:

```Python
>>> from ramda import *
>>> pipe(add, negate)(1, 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: <lambda>() takes 1 positional argument but 2 were given
```

My workaround is to wrap the leftmost function in `apply`. But it's not exactly the same, because you have to put the arguments into a list.

```Python
>>> pipe(apply(add), negate)([1, 2])
-3
```

Your `compose` has the same issue, but with the rightmost function.

Thank you.

**Comment by OlegAlexander** [comment]
To clarify, pipe's leftmost function should also accept 0 arguments. For example, this works in ramdajs:

```javascript
const theAnswer = () => 42
R.pipe(theAnswer, R.negate)() // -42
```

But not in Python:

```python
>>> the_answer = lambda: 42
>>> pipe(the_answer, negate)()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: <lambda>() missing 1 required positional argument: 'v'
```

**Comment by slavaGanzin** [comment]
I'll fix this when I'll find some time for this.

**Comment by OlegAlexander** [comment]
@slavaGanzin Thank you so much for fixing all these issues!

**Comment by slavaGanzin** [comment]
@OlegAlexander thank you for finding them. Waiting for new ones!
