### ISSUE TITLE
Versioning: Why the change from semver to time?

### ISSUE THREAD

**Issue by p-hebert** [slavaGanzin/ramda.py#16]
Hello! 👋 

Our company uses ramda as part of our stack and dependabot notified us that you published a new version for ramda just recently.

We noticed that you changed your versioning from semver to date of publishing. Why did you make that choice?
For us end users it removes some of the explicitness in the nature and scope of changes introduced, and requires a better readout of the commits & changeset. It's never really a bad thing to better understand your deps, but you know how it goes; can't be going to read the code like that for all our deps ;)

Could you please move back to semver?

Thank you!

**Comment by p-hebert** [comment]
Thanks @slavaGanzin!

**Comment by slavaGanzin** [comment]
Hi Phillip.

Semver is ok, I just found that many projects turns into date versioning. And it turns out for service libraries it's not acceptable.

Thanks for your point of view

**Comment by slavaGanzin** [comment]
@philippefutureboy https://pypi.org/project/ramda/#history
