### ISSUE TITLE
lt, lte, gt, gte are reversed

### ISSUE THREAD

**Issue by OlegAlexander** [slavaGanzin/ramda.py#19]
Hello,

It seems that `lt`, `lte`, `gt`, `gte` are reversed from their ramdajs counterparts.

In ramdajs:

```JavaScript
R.lt(2, 1); // false
R.lte(2, 1); // false
R.gt(2, 1); // true
R.gte(2, 1); // true
```

In Python:

```Python
>>> lt(2,1)
True
>>> lte(2,1)
True
>>> gt(2,1)
False
>>> gte(2,1)
False
```

I wonder if this was an intentional decision? Because in Ramda one almost always wants to know if the second parameter is less than the first, for example. But it is inconsistent with ramdajs.

A related question: How can I use the `R.__` placeholder function in Python? 

```JavaScript
R.lt(R.__, 1)(2); // false
```

PS. Sorry for all the issues I'm filing. I _really_ appreciate all the great work you're doing in porting Ramda to Python!!

**Comment by slavaGanzin** [comment]
It was just carelessness and not design https://github.com/slavaGanzin/ramda.py/commit/b76dbe691cb23aa58bc24e5d46d38fda810857f6

ramda.js choose this order for readability:
```
until(gt(100), multiply(2))(1)
```

Which is understandable as mere plain text: `multiply by 2 until is greater then 100`
@OlegAlexander I appreciate you for creating issues
