### ISSUE TITLE
Use  collections.abc.Iterable

### ISSUE THREAD

**Issue by peteut** [slavaGanzin/ramda.py#2]
Python 3.7 spits this warning:

`python3.7/site-packages/ramda/flatten.py:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working                                                                                                                                          
    from collections import Iterable`

**Comment by slavaGanzin** [comment]
@peteut Thanks for your notice
