### ISSUE TITLE
CI is broken.

### ISSUE THREAD

**Issue by jakobkolb** [slavaGanzin/ramda.py#27]
CI seems to be not working because some config is missing. 
As github actions are working very well as a CI provider for projects hosted on github (and are completely free for open source projects) I would suggest, we set it up. Also, If you agree, I would volunteer to do that. Let me know what you think.

Kind Regards

**Comment by slavaGanzin** [comment]
@jakobkolb Hi. Would be wonderful. I'll merge PR as soon as you done

**Comment by slavaGanzin** [comment]
@jakobkolb Just finished setup of Github actions. Please review. Any suggestions are welcome.
