### ISSUE TITLE
Map.py not working as expected

### ISSUE THREAD

**Issue by tavurth** [slavaGanzin/ramda.py#3]
Hi! Nice lib, I've been using for a little while.

I found this bug with `map` which doesn't behave the same as I'd expect from Ramda.js, perhaps there's something I'm missing?

```python3
print(
        pipe(
            map(lambda value: value + 1),
        )([1, 2, 3, 4, 5, 6, 7, 8, 9]),
    )
```

This gives me the error:

```error
Traceback (most recent call last):
    map(lambda value: value + 1),
TypeError: map() must have at least two arguments.
```

**Comment by slavaGanzin** [comment]
Hello.I can't reproduce this:

```python3
from ramda import *
print(pipe(map(lambda value: value + 1),)([1, 2, 3, 4, 5, 6, 7, 8, 9]),)

# [2, 3, 4, 5, 6, 7, 8, 9, 10]
```

It seems you just import map from ramda and using python one. Try this in your code:
```
print(map.__doc__)
```
it should print 'toolz.functoolz.curry' (ramda) and not 'type' (native)

**Comment by tavurth** [comment]
Hi @slavaGanzin!

Thanks for checking, it seems like I was mistaken. Now when I run the same code everything seems to be working fine.

Thank you for porting Ramda to Python, I'm enjoying the usage so far, and your docs are helpful!
