### ISSUE TITLE
Wrong result for aperture

### ISSUE THREAD

**Issue by mnieber** [slavaGanzin/ramda.py#30]
Hi, I found this problem

`ramda.aperture(2, [1, 2, 3, 4, 5, 6])` should return `[[1, 2], [2, 3], [3, 4], [4, 5], [5, 6]]` but it returns `[[1, 2], [2, 3], [3, 4], [4, 5], [6]]`

**Comment by slavaGanzin** [comment]
@mnieber thanks

**Comment by mnieber** [comment]
FYI my Github Copilot gave this solution: `[items[i : i + size] for i in range(0, len(items) - size + 1)]`

This solution so far has given me correct answers. I then played around with both expressions and they are different for the case of n = 1, so maybe you can still use the above?

**Comment by slavaGanzin** [comment]
Yours is better. good work
